
export const BRANDS_REQUEST = 'BRANDS_REQUEST';
export const BRANDS_SUCCESS = 'BRANDS_SUCCESS';
export const BRANDS_FAIL = 'BRANDS_FAIL';

export const BRAND_CREATE_REQUEST = 'BRAND_CREATE_REQUEST';
export const BRAND_CREATE_SUCCESS = 'BRAND_CREATE_SUCCESS';
export const BRAND_CREATE_FAIL = 'BRAND_CREATE_FAIL';

export const BRAND_UPDATE_REQUEST = 'BRAND_UPDATE_REQUEST';
export const BRAND_UPDATE_SUCCESS = 'BRAND_UPDATE_SUCCESS';
export const BRAND_UPDATE_FAIL = 'BRAND_UPDATE_FAIL';