export const CATEGORY_GROUPS_REQUEST = 'CATEGORY_GROUPS_REQUEST';
export const CATEGORY_GROUPS_SUCCESS = 'CATEGORY_GROUPS_SUCCESS';
export const CATEGORY_GROUPS_FAIL = 'CATEGORY_GROUPS_FAIL';

export const CATEGORY_GROUPS_WITH_CATEGORY_REQUEST = 'CATEGORY_GROUPS_WITH_CATEGORY_REQUEST';
export const CATEGORY_GROUPS_WITH_CATEGORY_SUCCESS = 'CATEGORY_GROUPS_WITH_CATEGORY_SUCCESS';
export const CATEGORY_GROUPS_WITH_CATEGORY_FAIL = 'CATEGORY_GROUPS_WITH_CATEGORY_FAIL';

export const CATEGORY_GROUP_CREATE_REQUEST = 'CATEGORY_GROUP_CREATE_REQUEST';
export const CATEGORY_GROUP_CREATE_SUCCESS = 'CATEGORY_GROUP_CREATE_SUCCESS';
export const CATEGORY_GROUP_CREATE_FAIL = 'CATEGORY_GROUP_CREATE_FAIL';

export const CATEGORY_GROUP_UPDATE_REQUEST = 'CATEGORY_GROUP_UPDATE_REQUEST';
export const CATEGORY_GROUP_UPDATE_SUCCESS = 'CATEGORY_GROUP_UPDATE_SUCCESS';
export const CATEGORY_GROUP_UPDATE_FAIL = 'CATEGORY_GROUP_UPDATE_FAIL';