export const CITIES_REQUEST = 'CITIES_REQUEST';
export const CITIES_REQUEST_SUCCESS = 'CITIES_REQUEST_SUCCESS';
export const CITIES_REQUEST_FAIL = 'CITIES_REQUEST_FAIL';

export const DISTRICTS_REQUEST = 'DISTRICTS_REQUEST';
export const DISTRICTS_REQUEST_SUCCESS = 'DISTRICTS_REQUEST_SUCCESS';
export const DISTRICTS_REQUEST_FAIL = 'DISTRICTS_REQUEST_FAIL';

export const MAP_CLEAR_STATE = 'MAP_CLEAR_STATE';
export const GEOCODE_REQUEST = 'GEOCODE_REQUEST';
export const GEOCODE_SUCCESS = 'GEOCODE_SUCCESS';
export const GEOCODE_FAIL = 'GEOCODE_FAIL';

export const LOCATION_REQUEST = 'LOCATION_REQUEST';
export const LOCATION_SUCCESS = 'LOCATION_SUCCESS';
export const LOCATION_FAIL = 'LOCATION_FAIL';
