export const COLOR_OPTIONS_REQUEST = 'COLOR_OPTIONS_REQUEST';
export const COLOR_OPTIONS_SUCCESS = 'COLOR_OPTIONS_SUCCESS';
export const COLOR_OPTIONS_FAIL = 'COLOR_OPTIONS_FAIL';

export const COLOR_OPTION_CREATE_REQUEST = 'COLOR_OPTION_CREATE_REQUEST';
export const COLOR_OPTION_CREATE_SUCCESS = 'COLOR_OPTION_CREATE_SUCCESS';
export const COLOR_OPTION_CREATE_FAIL = 'COLOR_OPTION_CREATE_FAIL';

export const COLOR_OPTION_UPDATE_REQUEST = 'COLOR_OPTION_UPDATE_REQUEST';
export const COLOR_OPTION_UPDATE_SUCCESS = 'COLOR_OPTION_UPDATE_SUCCESS';
export const COLOR_OPTION_UPDATE_FAIL = 'COLOR_OPTION_UPDATE_FAIL';

export const SIZE_OPTIONS_REQUEST = 'SIZE_OPTIONS_REQUEST';
export const SIZE_OPTIONS_SUCCESS = 'SIZE_OPTIONS_SUCCESS';
export const SIZE_OPTIONS_FAIL = 'SIZE_OPTIONS_FAIL';

export const SIZE_OPTION_CREATE_REQUEST = 'SIZE_OPTION_CREATE_REQUEST';
export const SIZE_OPTION_CREATE_SUCCESS = 'SIZE_OPTION_CREATE_SUCCESS';
export const SIZE_OPTION_CREATE_FAIL = 'SIZE_OPTION_CREATE_FAIL';

export const SIZE_OPTION_UPDATE_REQUEST = 'SIZE_OPTION_UPDATE_REQUEST';
export const SIZE_OPTION_UPDATE_SUCCESS = 'SIZE_OPTION_UPDATE_SUCCESS';
export const SIZE_OPTION_UPDATE_FAIL = 'SIZE_OPTION_UPDATE_FAIL';

export const QUANTITY_OPTIONS_REQUEST = 'QUANTITY_OPTIONS_REQUEST';
export const QUANTITY_OPTIONS_SUCCESS = 'QUANTITY_OPTIONS_SUCCESS';
export const QUANTITY_OPTIONS_FAIL = 'QUANTITY_OPTIONS_FAIL';

export const QUANTITY_OPTION_CREATE_REQUEST = 'QUANTITY_OPTION_CREATE_REQUEST';
export const QUANTITY_OPTION_CREATE_SUCCESS = 'QUANTITY_OPTION_CREATE_SUCCESS';
export const QUANTITY_OPTION_CREATE_FAIL = 'QUANTITY_OPTION_CREATE_FAIL';

export const QUANTITY_OPTION_UPDATE_REQUEST = 'QUANTITY_OPTION_UPDATE_REQUEST';
export const QUANTITY_OPTION_UPDATE_SUCCESS = 'QUANTITY_OPTION_UPDATE_SUCCESS';
export const QUANTITY_OPTION_UPDATE_FAIL = 'QUANTITY_OPTION_UPDATE_FAIL';

export const WAREHOUSE_GET_ALL_REQUEST = 'WAREHOUSE_GET_ALL_REQUEST';
export const WAREHOUSE_GET_ALL_SUCCESS = 'WAREHOUSE_GET_ALL_SUCCESS';
export const WAREHOUSE_GET_ALL_FAIL = 'WAREHOUSE_GET_ALL_FAIL';

export const WAREHOUSE_CREATE_ITEM_REQUEST = 'WAREHOUSE_CREATE_ITEM_REQUEST';
export const WAREHOUSE_CREATE_ITEM_SUCCESS = 'WAREHOUSE_CREATE_ITEM_SUCCESS';
export const WAREHOUSE_CREATE_ITEM_FAIL = 'WAREHOUSE_CREATE_ITEM_FAIL';

export const WAREHOUSE_UPDATE_ITEM_REQUEST = 'WAREHOUSE_UPDATE_ITEM_REQUEST';
export const WAREHOUSE_UPDATE_ITEM_SUCCESS = 'WAREHOUSE_UPDATE_ITEM_SUCCESS';
export const WAREHOUSE_UPDATE_ITEM_FAIL = 'WAREHOUSE_UPDATE_ITEM_FAIL';