
export const RATES_REQUEST = 'RATES_REQUEST';
export const RATES_SUCCESS = 'RATES_SUCCESS';
export const RATES_FAIL = 'RATES_FAIL';

export const RATE_CREATE_REQUEST = 'RATE_CREATE_REQUEST';
export const RATE_CREATE_SUCCESS = 'RATE_CREATE_SUCCESS';
export const RATE_CREATE_FAIL = 'RATE_CREATE_FAIL';

export const RATE_UPDATE_REQUEST = 'RATE_UPDATE_REQUEST';
export const RATE_UPDATE_SUCCESS = 'RATE_UPDATE_SUCCESS';
export const RATE_UPDATE_FAIL = 'RATE_UPDATE_FAIL';

export const RATE_DELETE_REQUEST = 'RATE_DELETE_REQUEST';
export const RATE_DELETE_SUCCESS = 'RATE_DELETE_SUCCESS';
export const RATE_DELETE_FAIL = 'RATE_DELETE_FAIL';

export const RATE_REPLY_CREATE_REQUEST = 'RATE_REPLY_CREATE_REQUEST';
export const RATE_REPLY_CREATE_SUCCESS = 'RATE_REPLY_CREATE_SUCCESS';
export const RATE_REPLY_CREATE_FAIL = 'RATE_REPLY_CREATE_FAIL';

export const RATE_REPLY_UPDATE_REQUEST = 'RATE_REPLY_UPDATE_REQUEST';
export const RATE_REPLY_UPDATE_SUCCESS = 'RATE_REPLY_UPDATE_SUCCESS';
export const RATE_REPLY_UPDATE_FAIL = 'RATE_REPLY_UPDATE_FAIL';

export const RATE_REPLY_DELETE_REQUEST = 'RATE_REPLY_DELETE_REQUEST';
export const RATE_REPLY_DELETE_SUCCESS = 'RATE_REPLY_DELETE_SUCCESS';
export const RATE_REPLY_DELETE_FAIL = 'RATE_REPLY_DELETE_FAIL';