export const STATISTICS_REQUEST = 'STATISTICS_REQUEST';
export const STATISTICS_SUCCESS = 'STATISTICS_SUCCESS';
export const STATISTICS_FAIL = 'STATISTICS_FAIL';

export const STATISTICS_CLEAR_STATE = 'STATISTICS_CLEAR_STATE';
