export const USERS_REQUEST = 'USERS_REQUEST';
export const USERS_SUCCESS = 'USERS_SUCCESS';
export const USERS_FAIL = 'USERS_FAIL';

export const USERS_GET_ALL_REQUEST = 'USERS_GET_ALL_REQUEST';
export const USERS_GET_ALL_SUCCESS = 'USERS_GET_ALL_SUCCESS';
export const USERS_GET_ALL_FAIL = 'USERS_GET_ALL_FAIL';


export const USERS_SEARCH_REQUEST = 'USERS_SEARCH_REQUEST';
export const USERS_SEARCH_SUCCESS = 'USERS_SEARCH_SUCCESS';
export const USERS_SEARCH_FAIL = 'USERS_SEARCH_FAIL';


export const USER_DETAIL_REQUEST = 'USER_DETAIL_REQUEST';
export const USER_DETAIL_SUCCESS = 'USER_DETAIL_SUCCESS';
export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_DETAIL_FAIL = 'USERDETAIL_FAIL';

export const EMPLOYEES_REQUEST = 'EMPLOYEES_REQUEST';
export const EMPLOYEES_SUCCESS = 'EMPLOYEES_SUCCESS';
export const EMPLOYEES_FAIL = 'EMPLOYEES_FAIL';