const ASK_LOW_DELIVERY = 'ask_slow_delivery';
const ASK_BEST_RATE = 'best_rate';
const ASK_BEST_VIEW = 'best_view';
const ASK_BEST_SELL = 'best_sell';
const ASK_BRANDS = 'ask_brands';
const ASK_CATEGORIES = "ask_categories";
const ASK_CATEGORIES_T_SHIRT = "ask_categories-t-shirt";
const ASK_CATEGORIES_SHIRT = "ask_categories-shirt";
const ASK_CATEGORIES_JACKET = "ask_categories-jacket";
const ASK_CATEGORIES_JEAN = "ask_categories-jean";
const ASK_PRODUCT = "ask_product";
const ASK_PERSON_BOT_CARE = "person_bot_care";
const ASK_HOW_TO_BUY = "ask_how_to_buy";

const T_SHIRT_CATEGORY_ID = "6031db48fa94700f38064e24";
const SHIRT_CATEGORY_ID = "60727d62f39072137c3b0858";
const JEAN_CATEGORY_ID = "6031db21fa94700f38064e23";
const JACKET_CATEGORY_ID = "60bba3ad13730619a09da37b";

module.exports = {
    ASK_LOW_DELIVERY: ASK_LOW_DELIVERY,
    ASK_BEST_RATE: ASK_BEST_RATE,
    ASK_BEST_VIEW: ASK_BEST_VIEW,
    ASK_BEST_SELL: ASK_BEST_SELL,
    ASK_BRANDS: ASK_BRANDS,
    ASK_CATEGORIES: ASK_CATEGORIES,
    ASK_PRODUCT: ASK_PRODUCT,
    ASK_PERSON_BOT_CARE: ASK_PERSON_BOT_CARE,
    ASK_HOW_TO_BUY: ASK_HOW_TO_BUY,
    T_SHIRT_CATEGORY_ID: T_SHIRT_CATEGORY_ID,
    SHIRT_CATEGORY_ID: SHIRT_CATEGORY_ID,
    JEAN_CATEGORY_ID: JEAN_CATEGORY_ID,
    JACKET_CATEGORY_ID: JACKET_CATEGORY_ID,
    ASK_CATEGORIES_T_SHIRT: ASK_CATEGORIES_T_SHIRT,
    ASK_CATEGORIES_SHIRT: ASK_CATEGORIES_SHIRT,
    ASK_CATEGORIES_JACKET: ASK_CATEGORIES_JACKET,
    ASK_CATEGORIES_JEAN: ASK_CATEGORIES_JEAN,
}