
export const BRANDS_REQUEST = 'BRANDS_REQUEST';
export const BRANDS_SUCCESS = 'BRANDS_SUCCESS';
export const BRANDS_FAIL = 'BRANDS_FAIL';

export const BRAND_REQUEST = 'BRAND_REQUEST';
export const BRAND_SUCCESS = 'BRAND_SUCCESS';
export const BRAND_FAIL = 'BRAND_FAIL';