
export const CARTS_REQUEST = 'CARTS_REQUEST';
export const CARTS_SUCCESS = 'CARTS_SUCCESS';
export const CARTS_FAIL = 'CARTS_FAIL';

export const RE_CARTS_SUCCESS = 'RE_CARTS_SUCCESS';
export const RE_CARTS_FAIL = 'RE_CARTS_FAIL';

export const CART_CREATE_REQUEST = 'CART_CREATE_REQUEST';
export const CART_CREATE_SUCCESS = 'CART_CREATE_SUCCESS';
export const CART_CREATE_FAIL = 'CART_CREATE_FAIL';

export const CART_UPDATE_REQUEST = 'CART_UPDATE_REQUEST';
export const CART_UPDATE_SUCCESS = 'CART_UPDATE_SUCCESS';
export const CART_UPDATE_FAIL = 'CART_UPDATE_FAIL';

export const CART_UPDATE_TYPE_REQUEST = 'CART_UPDATE_TYPE_REQUEST';
export const CART_UPDATE_TYPE_SUCCESS = 'CART_UPDATE_TYPE_SUCCESS';
export const CART_UPDATE_TYPE_FAIL = 'CART_UPDATE_TYPE_FAIL';

export const CART_DELETE_REQUEST = 'CART_DELETE_REQUEST';
export const CART_DELETE_SUCCESS = 'CART_DELETE_SUCCESS';
export const CART_DELETE_FAIL = 'CART_DELETE_FAIL';

export const CART_CLEAR_STATE = 'CART_CLEAR_STATE';