
export const COMMENTS_REQUEST = 'COMMENTS_REQUEST';
export const COMMENTS_SUCCESS = 'COMMENTS_SUCCESS';
export const COMMENTS_FAIL = 'COMMENTS_FAIL';

export const COMMENT_CREATE_REQUEST = 'COMMENT_CREATE_REQUEST';
export const COMMENT_CREATE_SUCCESS = 'COMMENT_CREATE_SUCCESS';
export const COMMENT_CREATE_FAIL = 'COMMENT_CREATE_FAIL';

export const COMMENT_UPDATE_REQUEST = 'COMMENT_UPDATE_REQUEST';
export const COMMENT_UPDATE_SUCCESS = 'COMMENT_UPDATE_SUCCESS';
export const COMMENT_UPDATE_FAIL = 'COMMENT_UPDATE_FAIL';

export const COMMENT_DELETE_REQUEST = 'COMMENT_DELETE_REQUEST';
export const COMMENT_DELETE_SUCCESS = 'COMMENT_DELETE_SUCCESS';
export const COMMENT_DELETE_FAIL = 'COMMENT_DELETE_FAIL';

export const REPLY_CREATE_REQUEST = 'REPLY_CREATE_REQUEST';
export const REPLY_CREATE_SUCCESS = 'REPLY_CREATE_SUCCESS';
export const REPLY_CREATE_FAIL = 'REPLY_CREATE_FAIL';

export const REPLY_UPDATE_REQUEST = 'REPLY_UPDATE_REQUEST';
export const REPLY_UPDATE_SUCCESS = 'REPLY_UPDATE_SUCCESS';
export const REPLY_UPDATE_FAIL = 'REPLY_UPDATE_FAIL';

export const REPLY_DELETE_REQUEST = 'REPLY_DELETE_REQUEST';
export const REPLY_DELETE_SUCCESS = 'REPLY_DELETE_SUCCESS';
export const REPLY_DELETE_FAIL = 'REPLY_DELETE_FAIL';