export const CITIES_REQUEST = 'CITIES_REQUEST';
export const CITIES_REQUEST_SUCCESS = 'CITIES_REQUEST_SUCCESS';
export const CITIES_REQUEST_FAIL = 'CITIES_REQUEST_FAIL';

export const DISTRICTS_REQUEST = 'DISTRICTS_REQUEST';
export const DISTRICTS_REQUEST_SUCCESS = 'DISTRICTS_REQUEST_SUCCESS';
export const DISTRICTS_REQUEST_FAIL = 'DISTRICTS_REQUEST_FAIL';