
export const MESSENGERS_REQUEST = 'MESSENGERS_REQUEST';
export const MESSENGERS_SUCCESS = 'MESSENGERS_SUCCESS';
export const MESSENGERS_FAIL = 'MESSENGERS_FAIL';

export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL';

export const FETCH_MESSAGES_REQUEST = 'FETCH_MESSAGES_REQUEST';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
export const FETCH_MESSAGES_FAIL = 'FETCH_MESSAGES_FAIL';

export const MESSENGER_DETAIL_REQUEST = 'MESSENGER_DETAIL_REQUEST';
export const MESSENGER_DETAIL_SUCCESS = 'MESSENGER_DETAIL_SUCCESS';
export const MESSENGER_UPDATE_CHECK = 'MESSENGER_UPDATE_CHECK';
export const MESSENGER_DETAIL_FAIL = 'MESSENGER_DETAIL_FAIL';

export const CLOSED_MESSAGE = 'CLOSED_MESSAGE';
export const CREATE_NEW_MESSAGE = 'CREATE_NEW_MESSAGE';
export const OPEN_DETAIL_MESSENGER = 'OPEN_DETAIL_MESSENGER';

export const CLEAR_MESSENGERS = 'CLEAR_MESSENGERS';

export const CODE_SOCKET_SEND_MESSAGE_FAIL = 20;
export const VERIFY_FAIL = 401;