export const NOTIFICATIONS_REQUEST = 'NOTIFICATIONS_REQUEST';
export const NOTIFICATIONS_SUCCESS = 'NOTIFICATIONS_SUCCESS';
export const NOTIFICATIONS_FAIL = 'NOTIFICATIONS_FAIL';

export const NOTIFICATION_UPDATE_REQUEST = 'NOTIFICATION_UPDATE_REQUEST';
export const NOTIFICATION_UPDATE_SUCCESS = 'NOTIFICATION_UPDATE_SUCCESS';
export const NOTIFICATION_UPDATE_FAIL = 'NOTIFICATION_UPDATE_FAIL';

export const NOTIFICATION_DELETE_REQUEST = 'NOTIFICATION_DELETE_REQUEST';
export const NOTIFICATION_DELETE_SUCCESS = 'NOTIFICATION_DELETE_SUCCESS';
export const NOTIFICATION_DELETE_FAIL = 'NOTIFICATION_DELETE_FAIL';

export const NOTIFICATION_CLEAR = 'NOTIFICATION_CLEAR';

export const NOTIFICATIONS_FEED_NEWS_REQUEST = 'NOTIFICATIONS_FEED_NEWS_REQUEST';
export const NOTIFICATIONS_FEED_NEWS_SUCCESS = 'NOTIFICATIONS_FEED_NEWS_SUCCESS';
export const NOTIFICATIONS_FEED_NEWS_FAIL = 'NOTIFICATIONS_FEED_NEWS_FAIL';

export const COMMENTED = "ĐÃ BÌNH LUẬN";
export const REPLIED_COMMENT = "ĐÃ PHẢN HỒI BÌNH LUẬN";
export const ORDERED = "ĐÃ ĐẶT HÀNG";
export const RATED = "ĐÃ ĐÁNH GIÁ";
export const REPLIED_RATE = "ĐÃ PHẢN HỒI ĐÁNH GIÁ";
export const CANCELED_ORDER = "ĐÃ HỦY ĐƠN HÀNG";
export const APPROVAL = "ĐÃ DUYỆT";




