
export const ORDERS_REQUEST = 'ORDERS_REQUEST';
export const ORDERS_VIEW_MORE_REQUEST = 'ORDERS_VIEW_MORE_REQUEST';
export const ORDERS_SUCCESS = 'ORDERS_SUCCESS';
export const ORDERS_FAIL = 'ORDERS_FAIL';

export const ORDER_REQUEST = 'ORDER_REQUEST';
export const ORDER_SUCCESS = 'ORDER_SUCCESS';
export const ORDER_FAIL = 'ORDER_FAIL';


export const ORDER_FETCH_PRODUCT_REQUEST = 'ORDER_FETCH_PRODUCT_REQUEST';
export const ORDER_FETCH_PRODUCT_SUCCESS = 'ORDER_FETCH_PRODUCT_SUCCESS';
export const ORDER_FETCH_PRODUCT_FAIL = 'ORDER_FETCH_PRODUCT_FAIL';

// export const RE_ORDERS_SUCCESS = 'RE_ORDERS_SUCCESS';
// export const RE_ORDERS_FAIL = 'RE_ORDERS_FAIL';

export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';

export const ORDER_CHANGE_TYPE_REQUEST = 'ORDER_CHANGE_TYPE_REQUEST';
export const ORDER_CHANGE_TYPE_SUCCESS = 'ORDER_CHANGE_TYPE_SUCCESS';
export const ORDER_CHANGE_TYPE_FAIL = 'ORDER_CHANGE_TYPE_FAIL';

export const ORDER_APPROVE_SUCCESS = 'ORDER_APPROVE_SUCCESS';
export const ORDER_APPROVE_FAIL = 'ORDER_APPROVE_FAIL';

export const SHIPPING_FEE_REQUEST = 'SHIPPING_FEE_REQUEST';
export const SHIPPING_FEE_SUCCESS = 'SHIPPING_FEE_SUCCESS';
export const SHIPPING_FEE_FAIL = 'SHIPPING_FEE_FAIL';

export const STORE_ADDRESSES_REQUEST = 'STORE_ADDRESSES_REQUEST';
export const STORE_ADDRESSES_SUCCESS = 'STORE_ADDRESSES_SUCCESS';
export const STORE_ADDRESSES_FAIL = 'STORE_ADDRESSES_FAIL';

export const CLEAR_STATE = 'CLEAR_STATE';

export const ORDER_UPDATE_SERIALS_REQUEST = 'ORDER_UPDATE_SERIALS_REQUEST';
export const ORDER_UPDATE_SERIALS_SUCCESS = 'ORDER_UPDATE_SERIALS_SUCCESS';
export const ORDER_UPDATE_SERIALS_FAIL = 'ORDER_UPDATE_SERIALS_FAIL';

// export const ORDER_UPDATE_REQUEST = 'ORDER_UPDATE_REQUEST';
// export const ORDER_UPDATE_SUCCESS = 'ORDER_UPDATE_SUCCESS';
// export const ORDER_UPDATE_FAIL = 'ORDER_UPDATE_FAIL';

// export const ORDER_UPDATE_TYPE_REQUEST = 'ORDER_UPDATE_TYPE_REQUEST';
// export const ORDER_UPDATE_TYPE_SUCCESS = 'ORDER_UPDATE_TYPE_SUCCESS';
// export const ORDER_UPDATE_TYPE_FAIL = 'ORDER_UPDATE_TYPE_FAIL';

// export const ORDER_DELETE_REQUEST = 'ORDER_DELETE_REQUEST';
// export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS';
// export const ORDER_DELETE_FAIL = 'ORDER_DELETE_FAIL';


export const PAY_URL_REQUEST = 'PAY_URL_REQUEST';
export const PAY_URL_SUCCESS = 'PAY_URL_SUCCESS';
export const PAY_URL_FAIL = 'PAY_URL_FAIL';
