export const COLOR_OPTIONS_REQUEST = 'COLOR_OPTIONS_REQUEST';
export const COLOR_OPTIONS_SUCCESS = 'COLOR_OPTIONS_SUCCESS';
export const COLOR_OPTIONS_FAIL = 'COLOR_OPTIONS_FAIL';

export const SIZE_OPTIONS_REQUEST = 'SIZE_OPTIONS_REQUEST';
export const SIZE_OPTIONS_SUCCESS = 'SIZE_OPTIONS_SUCCESS';
export const SIZE_OPTIONS_FAIL = 'SIZE_OPTIONS_FAIL';

export const QUANTITY_OPTIONS_REQUEST = 'QUANTITY_OPTIONS_REQUEST';
export const QUANTITY_OPTIONS_SUCCESS = 'QUANTITY_OPTIONS_SUCCESS';
export const QUANTITY_OPTIONS_FAIL = 'QUANTITY_OPTIONS_FAIL';
