
export const PRODUCTS_REQUEST = 'PRODUCTS_REQUEST';
export const PRODUCTS_SUCCESS = 'PRODUCTS_SUCCESS';
export const PRODUCTS_FAIL = 'PRODUCTS_FAIL';

export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST';
export const PRODUCT_DETAIL_SUCCESS = 'PRODUCT_DETAIL_SUCCESS';
export const PRODUCT_DETAIL_FAIL = 'PRODUCT_DETAIL_FAIL';


export const PRODUCT_HOMEPAGE_REQUEST = 'PRODUCT_HOMEPAGE_REQUEST';
export const PRODUCT_HOMEPAGE_SUCCESS = 'PRODUCT_HOMEPAGE_SUCCESS';
export const PRODUCT_HOMEPAGE_FAIL = 'PRODUCT_HOMEPAGE_FAIL';

export const PRODUCTS_VIEW_MORE_REQUEST = 'PRODUCTS_VIEW_MORE_REQUEST';

export const RECOMMENDED_PRODUCT_REQUEST = 'RECOMMENDED_PRODUCT_REQUEST';
export const RECOMMENDED_PRODUCT_SUCCESS = 'RECOMMENDED_PRODUCT_SUCCESS';
export const RECOMMENDED_PRODUCT_FAIL = 'RECOMMENDED_PRODUCT_FAIL';
