export const INITITION = 'INITITION';
export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_VERIFY_OTP_REQUEST = 'USER_VERIFY_OTP_REQUEST';
export const USER_VERIFY_OTP_SUCCESS = 'USER_VERIFY_OTP_SUCCESS';
export const USER_VERIFY_OTP_FAIL = 'USER_VERIFY_OTP_FAIL';

export const USER_FORGOTPASSWORD_REQUEST = 'USER_FORGOTPASSWORD_REQUEST';
export const USER_FORGOTPASSWORD_SUCCESS = 'USER_FORGOTPASSWORD_SUCCESS';
export const USER_FORGOTPASSWORD_FAIL = 'USER_FORGOTPASSWORD_FAIL';

export const USER_RESET_PASSSWORD_REQUEST = 'USER_RESET_PASSSWORD_REQUEST';
export const USER_RESET_PASSSWORD_SUCCESS = 'USER_RESET_PASSSWORD_SUCCESS';
export const USER_RESET_PASSSWORD_FAIL = 'USER_RESET_PASSSWORD_FAIL';

export const USER_INFORM = 'USER_INFORM';

export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_AVATAR_REQUEST = 'USER_AVATAR_REQUEST';
export const USER_AVATAR_SUCCESS = 'USER_AVATAR_SUCCESS';
export const USER_AVATAR_FAIL = 'USER_AVATAR_FAIL';

export const USER_PROFLE_REQUEST = 'USER_PROFLE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';

export const USER_PROFLE_UPDATE_REQUEST = 'USER_PROFLE_UPDATE_REQUEST';
export const USER_PROFILE_UPDATE_SUCCESS = 'USER_PROFILE_UPDATE_SUCCESS';
export const USER_PROFILE_UPDATE_FAIL = 'USER_PROFILE_UPDATE_FAIL';

export const USER_CHANGEPASSWORD_REQUEST = 'USER_CHANGEPASSWORD_REQUEST';
export const USER_CHANGEPASSWORD_SUCCESS = 'USER_CHANGEPASSWORD_SUCCESS';
export const USER_CHANGEPASSWORD_FAIL = 'USER_CHANGEPASSWORD_FAIL';

export const USER_ADDRESSES_REQUEST = 'USER_ADDRESSES_REQUEST';
export const USER_ADDRESSES_SUCCESS = 'USER_ADDRESSES_SUCCESS';
export const USER_ADDRESSES_FAIL = 'USER_ADDRESSES_FAIL';

export const USER_ADD_ADDRESS_REQUEST = 'USER_ADD_ADDRESS_REQUEST';
export const USER_ADD_ADDRESS_SUCCESS = 'USER_ADD_ADDRESS_SUCCESS';
export const USER_ADD_ADDRESS_FAIL = 'USER_ADD_ADDRESS_FAIL';

export const USER_UPDATE_ADDRESS_REQUEST = 'USER_UPDATE_ADDRESS_REQUEST';
export const USER_UPDATE_ADDRESS_SUCCESS = 'USER_UPDATE_ADDRESS_SUCCESS';
export const USER_UPDATE_ADDRESS_FAIL = 'USER_UPDATE_ADDRESS_FAIL';

export const USER_DELETE_ADDRESS_REQUEST = 'USER_DELETE_ADDRESS_REQUEST';
export const USER_DELETE_ADDRESS_SUCCESS = 'USER_DELETE_ADDRESS_SUCCESS';
export const USER_DELETE_ADDRESS_FAIL = 'USER_DELETE_ADDRESS_FAIL';

export const USER_CHANGEPHONE_REQUEST = 'USER_CHANGEPHONE_REQUEST';
export const USER_CHANGEPHONE_SUCCESS = 'USER_CHANGEPHONE_SUCCESS';
export const USER_CHANGEPHONE_FAIL = 'USER_CHANGEPHONE_FAIL';

export const CLEAR_INFORM_PROFILE = 'CLEAR_INFORM_PROFILE';
export const CLEAR_INFORM_CHANGEPASSWORD = 'CLEAR_INFORM_CHANGEPASSWORD';
export const CLEAR_INFORM_CHANHEPHONE = 'CLEAR_INFORM_CHANHEPHONE';


export const TIME_OUT_REQUEST = 'TIME_OUT_REQUEST';