require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'TLCN_FashionStore' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'


  pod 'RNGoogleSignin', :path => '../node_modules/@react-native-google-signin/google-signin'

  pod 'RNCPicker', :path => '../node_modules/@react-native-community/picker'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  target 'TLCN_FashionStoreTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end